<?php
/**
 * Created by PhpStorm.
 * User: zhoutian
 * Date: 2019/3/23
 * Time: 15:03
 */

namespace app\controllers;


use app\behaviors\DepartmentBehavior;
use app\behaviors\LoginBehavior;
use app\logic\TaskForm;
use app\models\Department;
use app\models\Task;
use app\models\TaskRecord;
use app\models\User;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\web\UrlManager;

class DailyController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => LoginBehavior::className(),
            ]
        ];
    }

    public function actionIndex()
    {
        $department = \Yii::$app->request->get('department');
        $username = \Yii::$app->request->get('username');
        $content = \Yii::$app->request->get('content');
        $departmentList = Department::getVisibleDepartment();
        $query = Task::find()->alias('t');
        $query->leftJoin(['u' => User::tableName()], 'u.id = t.user_id');
        if ($department && $departmentList[$department]) {
            $query->where(['u.department' => $department]);
            if($username)
                $query->andWhere(['like','u.realname',$username]);
        } else {
            $query->where(['u.id' => \Yii::$app->user->id]);
        }
        if($content)
            $query->andwhere(['like','t.content',$content]);
        $pagination = new Pagination(['totalCount' => $query->count(), 'defaultPageSize' => 20]);
        $query->orderBy('t.id desc')->select('u.*,t.*');
        $list = $query->offset($pagination->offset)->limit($pagination->limit)->asArray()->all();
        foreach($list as $k=>$v) {
            $list[$k]['records'] = TaskRecord::find()->where(['task_id' => $v['id']])->all();
        }
        $params = \Yii::$app->request->getQueryParams();
        return $this->render('daily', [
            'list' => $list,
            'departmentList' => $departmentList,
            'pagination' => $pagination,
            'params' => $params,
            'results' => \Yii::$app->params['result']
        ]);
    }

    public function actionEdit()
    {
        if (\Yii::$app->request->isPost) {
            $taskForm = new TaskForm();
            $taskForm->attributes = \Yii::$app->request->post();
            $taskForm->user_id = \Yii::$app->user->id;
            $taskForm->records = \Yii::$app->request->post('records');
            $taskForm->save();
            return $this->redirect(['daily/detail', 'id' => $taskForm->id]);
        }
        $id = \Yii::$app->request->get('id');
        $task = Task::findOne([
            'id' => $id,
            'user_id' => \Yii::$app->user->id,
        ]);
        return $this->render('daily-edit', [
            'task' => $task,
            'results' => \Yii::$app->params['result']
        ]);
    }

    public function actionDetail()
    {

        $id = \Yii::$app->request->get('id');
        $task = Task::findOne($id);
        switch(\Yii::$app->user->identity->level) {
            case 3:
                $taskUser = User::findOne($task->user_id);
                $visible = $taskUser->department == \Yii::$app->user->identity->department;
                break;
            case 4:
                $visible = true;
                break;
            case 1:
            case 2:
            default:
                $visible = $task->user_id == \Yii::$app->user->id;
                break;
        }
        if(!$visible)
            exit('permission denied');
        return $this->render('daily-detail', [
            'task' => $task
        ]);
    }

    public function actionDelete()
    {
        $id = \Yii::$app->request->get('id');
        $user = User::findOne($id);
        if ($user->username == 'admin')
            return $this->renderJson([
                'code' => 1,
                'msg' => "admin不能删除"
            ]);
        $user->delete();
        return $this->renderJson([
            'code' => 0,
            'msg' => "删除成功"
        ]);
    }

    public function actionDeleteAll()
    {
        $ids = \Yii::$app->request->get('ids');
        $idsArray = explode(',', $ids);
        foreach ($idsArray as $id) {
            $user = User::findOne($id);
            if ($user->username == 'admin')
                continue;
            $user->delete();
        }
        return $this->renderJson([
            'code' => 0,
            'msg' => "删除成功"
        ]);
    }
}